### ISSUE TITLE
Node Reconstructed Similarity

### ISSUE THREAD

**Issue by dpasch01** [zexihuang/POLE#1]
Hello, 

In the paper you mention node "reconstructed similarity". 
Could someone use the similarity between nodes to characterize them as friendly or hostile?
Also, how can we measure this "reconstructed similarity" ?

I followed part of your code with the pairwise kernels and scale, but the values are not limited to [-1, 1].

Thank you.

**Comment by zexihuang** [comment]
Hi Demetris,

Thanks for the questions.

1. The pairwise similarity between nodes is designed to capture their friendly/hostile relationship, so you can definitely use it for that. 
2. The reconstructed similarity is computed as the inner product between node embeddings. For visualization purposes in the paper, we scale its magnitude (i.e., dividing by a constant) so that its values fall in [-1, 1]. Scaling is not needed for using the similarity in ranking/classification.

Hope this answers your questions!

Best regards,
Zexi

**Comment by dpasch01** [comment]
Thank you for your answer.

Without any scaling or normalization, I get values like -100 and 60. How could I assume the boundaries between positive, neutral, and negative relationships? In your paper you present figure 5 with a clear separation of the three in a scale from -1 to 1.

**Comment by zexihuang** [comment]
Figure 5 in the paper is based on the synthetic LFR network (as visualized in Figure 1(a)), which is considered highly polarized and it is easy to separate the three types of relationships. Real-world networks are usually harder. We have drawn the scatter plots of signed and unsigned similarity for them as Figures 8 and 11 in the paper, along with the decision boundary. In our signed link prediction task, we select the decision boundaries for positive/negative vs neutral based on the k values to compute precision@k. You can also use other metrics (e.g., F1-score) to select the decision boundary.

**Comment by dpasch01** [comment]
OK! Thank you very much!
